export const useStyles = theme => ({
  adminMainContainer: {
    maxWidth: "100% !important",
    display: "flex",
    justifyContent: "space-between",
    boxShadow: "none !important",
    backgroundColor: `${theme.palette.text.offWhiteColor} !important`,
    "& .MuiGrid-grid-lg-4": {
      flexBasis: "32.33%",
      "@media(max-width:1280px)": {
        maxWidth: "100%",
        marginTop: 25,
      },
    },
    "& .MuiGrid-grid-lg-8": {
      flexBasis: "65.66%",
      "@media(max-width:1280px)": { maxWidth: "100%" },
    },
    "@media(max-width:1280px)": { flexDirection: "column" },
  },
  card: {
    borderRadius: 4,
    boxShadow: "0 1px 1px 0 rgba(0,0,0,0.07), 0 2px 1px -1px rgba(0,0,0,0.07), 0 1px 3px 0 rgba(0,0,0,0.1)",
    backgroundColor: theme.palette.text.white,
    "& h3": {
      padding: "0 22px",
      borderBottomWidth: 1,
      borderBottomStyle: "solid",
      borderBottomColor: theme.palette.text.gray1,
      margin: 0,
      color: theme.palette.text.darkShadedGray,
      fontSize: 20,
      fontWeight: 600,
      lineHeight: "50px",
    },
    "& hr": {
      margin: "0 32px 0 25px",
      backgroundColor: theme.palette.text.inputBoxBorder,
      opacity: 0.5,
    },
  },
  textField: {
    position: "relative",
    "& span": {
      padding: "0 6px",
      position: "absolute",
      top: -7,
      left: 10,
      background: theme.palette.text.white,
      color: theme.palette.text.darkShadedGray,
      fontSize: 12,
      letterSpacing: 0.4,
    },
    "& input": {
      boxSizing: "border-box",
      padding: "15px 10px",
      borderWidth: 1,
      borderStyle: "solid",
      borderColor: "rgba(25,25,25,0.32)",
      borderRadius: 4,
      color: theme.palette.text.darkShadedGray,
      fontSize: 16,
      letterSpacing: 0.15,
      lineHeight: "24px",
    },
  },
  ethereumAddressMainContainer: {
    padding: "21px 32px 47px 25px",
  },
  ethereumAddressContainer: {
    marginBottom: 24,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    "& div": {
      "@media(max-width:960px)": { flex: "1 0 0" },
      "@media(max-width:600px)": {
        width: "100%",
        marginBottom: 15,
      },
    },
    "& input": {
      width: 411,
      "@media(max-width:960px)": { width: "100%" },
    },
    "& p": {
      padding: "0 18px",
      margin: 0,
      color: theme.palette.text.lightShadedGray,
      fontSize: 14,
      letterSpacing: 0.25,
      lineHeight: "20px",
      "@media(max-width:960px)": { flex: "1 0 0" },
    },
    "@media(max-width:600px)": { flexDirection: "column" },
  },
  foundationMemberContainer: {
    padding: "53px 32px 25px 25px",
    "& h4": {
      margin: 0,
      color: theme.palette.text.darkShadedGray,
      fontSize: 18,
      lineHeight: "23px",
    },
  },
  table: {
    marginTop: 32,
    "& .MuiTableCell-root:last-child": { paddingRight: 0 },
  },
  tableHeader: {
    "& th": {
      border: "none",
      padding: "0 0 24px",
      margin: 0,
      color: theme.palette.text.darkShadedGray,
      fontFamily: theme.typography.primary.main,
      fontSize: 16,
    },
    "@media(max-width:600px)": { display: "none" },
  },
  tableData: {
    "& tr": {
      "@media(max-width:600px)": {
        display: "flex",
        flexDirection: "column",
        borderTopWidth: 1,
        borderTopStyle: "solid",
        borderTopColor: theme.palette.text.lightGray,
      },
    },
    "& td": {
      padding: "9px 0",
      borderTopWidth: 1,
      borderTopStyle: "solid",
      borderTopColor: theme.palette.text.lightGray,
      borderBottom: "none",
      color: theme.palette.text.mediumShadeGray,
      fontFamily: theme.typography.primary.main,
      fontSize: 14,
      "& > span": {
        display: "none",
        color: theme.palette.text.darkShadedGray,
        fontSize: 16,
        fontWeight: 600,
        "@media(max-width:600px)": { display: "block" },
      },
      "@media(max-width:600px)": {
        maxWidth: "100%",
        border: "none",
        flexDirection: "column",
        textAlign: "left",
      },
    },
  },
  address: {
    boxSizing: "border-box",
    maxWidth: 300,
    paddingRight: "25px !important",
    wordBreak: "break-all",
  },
  inputFieldContainer: {
    padding: "15px 21px 40px",
    "& input": {
      width: "100%",
      marginBottom: 26,
    },
  },
  btnContainer: {
    paddingBottom: 25,
    display: "flex",
    justifyContent: "center",
  },
});
