export const useStyles = theme => ({
  accountBalanceContainer: {
    maxWidth: 411,
    paddingBottom: 27,
    borderRadius: 4,
    marginBottom: 30,
    backgroundColor: theme.palette.text.white,
    boxShadow: "0 1px 1px 0 rgba(0,0,0,0.07), 0 2px 1px -1px rgba(0,0,0,0.07), 0 1px 3px 0 rgba(0,0,0,0.1)",
    flexBasis: "30%",
    "& h3": {
      padding: "0 22px",
      borderBottomWidth: 1,
      borderBottomStyle: "solid",
      borderBottomColor: theme.palette.text.gray1,
      margin: 0,
      color: theme.palette.text.darkShadedGray,
      fontSize: 20,
      fontWeight: 600,
      lineHeight: "50px",
    },
    "@media(max-width:960px)": {
      maxWidth: "100%",
      marginTop: 25,
      marginLeft: 0,
      flexBasis: "100%",
    },
  },
  demo: { backgroundColor: "red" },
  warningBox: {
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: theme.palette.text.warningBoxBorder,
    borderRadius: 4,
    padding: "13px 20px",
    margin: "28px 20px 0",
    backgroundColor: theme.palette.text.warningBoxBg,
    "& p, & span": {
      color: theme.palette.text.alertBoxColor,
      fontFamily: theme.typography.primary.main,
      fontSize: 14,
      lineHeight: "20px",
      letterSpacing: 0.25,
      textAlign: "left",
    },
    "& p": { paddingTop: 20 },
    "& a": {
      color: "#067AD7",
      fontWeight: "bold",
    },
  },
  btnContainer: {
    margintop: 24,
    display: "flex",
    justifyContent: "center",
  },
});
